env:
  NODE_VERSION: "16"

steps:
  - label: ":cloud: Publish"
    if: build.tag != null
    commands:
      - npm config set "//registry.npmjs.org/:_authToken" $${NPM_TOKEN}
      - yarn --frozen-lockfile
      - npm publish
    plugins:
      - docker-login#v2.1.0:
          username: localzservice
          password-env: DOCKER_LOGIN_PASSWORD
      - docker#v3.11.0:
          image: localz/buildkite-node:${NODE_VERSION}
          environment:
            - NPM_TOKEN
